version: '3'
services:
  nodeserver:
    build: .
    ports:
      - "3333:3333"
    command: npm run dev
    volumes:
      - .:/app/
  rethinkdb:
    image: rethinkdb
    command: rethinkdb --bind all
    volumes:
      - '.:/data'
    ports:
      - "8888:8080"
      - "28015:28015"
