version: '3'
services:
  rethinkdb:
    image: rethinkdb
    command: rethinkdb --bind all
    volumes:
      - '.:/data'
    ports:
      - "8888:8080"
      - "28015:28015"
  # nfl-api:
  #   image: graborg/nfl-api:1.1.2
  #   depends_on:
  #     - rethinkdb
  #   ports:
  #     - "7331:7331"
  # nfl-ui:
  #   image: graborg/nfl:1.3.4
  #   ports:
  #     - '3000:3000'