version: '3'
services:
  nodeserver:
    build: .
    ports:
      - "3333:3333"
    command: npm run dev
    volumes:
      - ./lib:/app/assets
      - ./components:/app/components
      - ./pages:/app/pages
      - ./middleware:/app/middleware
      - ./plugins:/app/plugins
      - ./utils:/app/utils
      - ./utils.js:/app/utils.js
      - ./nuext.config.js:/app/nuxt.config.js
  rethinkdb:
    image: rethinkdb
    command: rethinkdb --bind all
    volumes:
      - '.:/data'
    ports:
      - "8888:8080"
      - "28015:28015"
