version: '3'
services:
  rethinkdb:
    image: rethinkdb
    command: rethinkdb --bind all
    volumes:
      - '.:/data'
    ports:
      - "8888:8080"
      - "28015:28015"
#     networks:
#       - db
#   nfl-api:
#     image: graborg/nfl-api:1.4.1
#     depends_on:
#       - rethinkdb
#     environment:
#       - rethinkdb__host=rethinkdb
#       - frontendDomain=http://localhost:3000
#     ports:
#       - "7331:7331"
#     networks:
#       - nfl
#       - db
#   nfl-ui:
#     build: .
#     ports:
#       - '3000:3000'
#     networks:
#       - nfl
# networks:
#   nfl:
#     external: true
#   db:
#     external: true